AWSTemplateFormatVersion: "2010-09-09"
Description: "Automaticed creation of all infraestructure to support POC case 4."

Parameters:
  DatabaseInGlue:
    Type: String
    MinLength: "4"
    Default: "db-poc-case-4"
    Description: Name of DB in AWS Glue database for POC case 4

  StorageLayerS3:
    Type: String
    MinLength: "4"
    Default: "s3-storage-layer"
    Description: Name of S3 for POC case 4


Resources:
  ## Resource to store all table in format iceberg
  DataStorageLayer:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref StorageLayerS3
      PublicAccessBlockConfiguration:
        BlockPublicAcls: False
        BlockPublicPolicy: False
        IgnorePublicAcls: False
        RestrictPublicBuckets: False
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred

  ## Resource to prepare database (AWS GLUE)
  DBGlue:
    Type: "AWS::Glue::Database"
    Properties:
      DatabaseInput:
        Description: "Database to store all tables in glue"
        Name: !Ref DatabaseInGlue
      CatalogId: !Ref AWS::AccountId ## reference the same AWS account

  ## Role in aws glue job
  AWSGlueJobRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:  "*"
                Resource: "*"
      Path: "/" 

  ## AWS Glue job
  CSVToIcebergGlueJob:
    Type: "AWS::Glue::Job"
    Properties:
      Role: !Ref AWSGlueJobRole
      Name: "CSVToIcebergTransform"
      Command : 
        Name: "glueetl"
        PythonVersion: "3.9"
        ScriptLocation: "s3://s3-storage-layer/script/emulator_glue_job.py"
      DefaultArguments:
        "bucket_origin": "s3-storage-layer/raw-csv-file"
        "bucket_destiny": "s3-storage-layer/athena"
        "object_bucket_origin": "faked_orders.csv"
        "object_bucket_destiny": "faked_orders.parquet"
      MaxRetries: 0
      Description: "transform files from CSV format to iceberg format script"




