'''

SQL:

1. Get all orders a datetime range:

    SELECT "t"."creation",  "t"."crossdocking", "t"."pickup_address", "t"."drop_address", "t"."product_description", "t"."product_price", "t"."product_weight", "cl"."business_name", "cl"."comercial_name", "s"."name" as "service_name", "c"."name" as "city_name"
FROM "db-poc-case-1"."trackcode_table" as "t"
RIGHT JOIN "db-poc-case-1"."client_table"  as "cl"
    on "t"."client_id" = "cl"."id"
RIGHT JOIN "db-poc-case-1"."service_table"  as "s"
    on "t"."service_id" = "s"."id"
RIGHT JOIN "db-poc-case-1"."city_table"  as "c"
    on "cl"."city_id" = "c"."id"
WHERE "t"."creation" BETWEEN '2022-11-05' and '2022-11-15';

2. Get all money generated by the routes and detailed in range of datetime.

3. Get the most visited location from the trackcodes in range of datetime.
4. The number of trackcode generated based date in range of datetime.
5. The number of orders by code generated during a date range.
6. The number of trackcodes lost.
7. The most required service using during a date range.
8. Check how many orders are success delivery before the promise time in date range.

'''